
build_image:
  image: docker:latest
  tags:
    - linux
    - ci.inria.fr
    - small
  script:
    - echo "Building docker image $CI_REGISTRY"
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/pberg/bedrock:latest .
    - docker push $CI_REGISTRY/pberg/bedrock:latest
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

pages:
  image: registry.gitlab.inria.fr/pberg/bedrock:latest
  tags:
    - linux
    - ci.inria.fr
    - small
  script:
    - bedrock export ./docs/ --root-url=$CI_PROJECT_NAME --title=$CI_PROJECT_TITLE
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
