image: docker:latest

before_script:
  - echo "Building docker image ($CI_REGISTRY:latest)"
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
build_image:
  tags:
    - linux
    - ci.inria.fr
    - small
  script:
    - docker build -t $CI_REGISTRY:latest .
    - docker push $CI_REGISTRY:latest
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
