name: Build and Push Docker

jobs:
  build_and_push:
    name: "Build and push"
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Build and push Docker images
        uses: docker/build-push-action@v6.12.0
        with:
          context: .
          file: ./Dockerfile
          push: true
